### ISSUE TITLE
Please, add typescript types definitions to this module

### ISSUE THREAD

**Issue by micalevisk** [remarkjs/remark-unlink#3]
### Problem

I'm using this lib with TypeScript and the TS compiler complains about the lack of typings:

```
Could not find a declaration file for module 'remark-unlink'. 'xxxx/node_modules/remark-unlink/index.js' implicitly has an 'any' type.
  Try `npm install @types/remark-unlink` if it exists or add a new declaration (.d.ts) file containing `declare module 'remark-unlink';`
ts(7016)
```

### Solution

Create a `types/index.d.ts` file pretty much like [strip-markdown](https://github.com/remarkjs/strip-markdown/blob/625506cb8377c076663001273fde30f9ffae03ee/types/index.d.ts), and update the `files` field of your `package.json`.

I think that the following will be enough:

```typescript
declare module 'remark-unlink' {
  import type { Plugin } from 'unified';

  /**
   * Remark plugin to remove Markdown links, images, references, and definitions.
   */
  declare const remarkUnlink: Plugin;

  export = remarkUnlink;
}
```

**Comment by wooorm** [comment]
Pull requests are welcome!
With ts definitions we tend to follow definitly typed's policy of including the typings, dtslint, and a type test.
The process is usually pretty quick, you can see some examples here: remarkjs/strip-markdown#21, remarkjs/remark-external-links#18, and remarkjs/remark-footnotes#4

Closing this issue out, as it is a goal across all 300+ unifier/remark repos, and keeping an open issue for each is a bit much :sweat_smile:
